# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multi_regression_train <- function(train_matrix, outcome_index, sample_weight_index, use_sample_weights, mtry, num_trees, min_node_size, sample_fraction, honesty, honesty_fraction, honesty_prune_leaves, alpha, imbalance_penalty, clusters, samples_per_cluster, compute_oob_predictions, num_threads, seed, mahalanobis, sigma) {
    .Call(`_rfmultiregression_multi_regression_train`, train_matrix, outcome_index, sample_weight_index, use_sample_weights, mtry, num_trees, min_node_size, sample_fraction, honesty, honesty_fraction, honesty_prune_leaves, alpha, imbalance_penalty, clusters, samples_per_cluster, compute_oob_predictions, num_threads, seed, mahalanobis, sigma)
}

multi_regression_predict <- function(forest_object, train_matrix, test_matrix, num_outcomes, num_threads) {
    .Call(`_rfmultiregression_multi_regression_predict`, forest_object, train_matrix, test_matrix, num_outcomes, num_threads)
}

multi_regression_predict_oob <- function(forest_object, train_matrix, num_outcomes, num_threads) {
    .Call(`_rfmultiregression_multi_regression_predict_oob`, forest_object, train_matrix, num_outcomes, num_threads)
}

